export const icons = {
  SEARCH_ICON: "/icons/search.svg",
  USER_ICON: "/icons/user-icon.svg",
  SHOPPING_CART: "/icons/shopping-cart.svg",
  ARROW: "/icons/arrow.svg",
  CLOSE: "/icons/close.svg",
  DESIGNER: "/icons/designer.svg",
  PARFUME1_ICON: "/icons/perfume1.svg",
  PARFUME2_ICON: "/icons/perfume2.svg",
  PARFUME3_ICON: "/icons/perfume3.svg",
  PARFUME4_ICON: "/icons/perfume4.svg",
  PARFUME5_ICON: "/icons/perfume5.svg",
  HEART_OUTLINE: "/icons/heartOutline.svg",
  HEART_FILL: "/icons/heartFill.svg",
  STAR_ICON: "/icons/vector.svg",
  STAR_ICON_OUTLINE: "/icons/vectorOutFill.svg",
  ARROW_RIGHT_ICON: "/icons/rightArrow.svg",
  ARROW_LEFT_ICON: "/icons/leftArrow.svg",
  BLOG_IMAGE1: "/icons/image 6.svg",
  BLOG_IMAGE2: "/icons/Rectangle 39.svg",
  BLOG_IMAGE3: "/icons/Rectangle 104.svg",
  OFFER_IMAGE1: "/icons/115030_full 1.svg",
  OFFER_IMAGE2: "/icons/127566_full 1.svg",
  OFFER_IMAGE3: "/icons/156143_full 1.svg",
  OFFER_IMAGE4: "/icons/156144_full 1.svg",
  USER_ELLIPSE: "/icons/Ellipse 41.svg",
  OFFER_IMAGE_BIG: "/icons/image_full.svg",
  CROSS_ICON: "/icons/imagebot_2.svg",
  SCENT_ICON: "/icons/scentIcon.jpg",
  CHECK_ICON: "/icons/icon _circle check_.svg",
  ARROW_LEFT_BLACK_ICON: "/icons/arrow_left_Black.svg",
  ARROW_RIGHT_GRAY_ICON: "/icons/arrow_right_gray.svg",
  ADD_ICON: "/icons/add1.svg",
  ARROW_DOWN_ICON: "/icons/arrow_down.svg",
  REMOVE_ICON: "/icons/remove 1.svg",
  WAITING_ICON: "/icons/🦆 icon _pie chart 25_.svg",
  CANCEL_ICON: "/icons/cancel.svg",
  SUCCESS_ICON: "/icons/success.svg",
  VERIFICATION: "/icons/verification.svg",
  ARROW_UP_ICON: "/icons/arrrow_up.svg",
  UP_LOAD_IMAGE_ICON: "/icons/Group 4345.png",
  PLUS_ADD_IMAGE_ICON: "/icons/Group 24.svg",
} as const;

export const socialIcons = {
  INSTAGRAM: "/icons/social/instagram.svg",
  TELEGRAM: "/icons/social/telegram.svg",
  VIBER: "/icons/social/viber.svg",
};
