export const icons = {
  SEARCH_ICON: "/images/icons/search.svg",
  USER_ICON: "/images/icons/user-icon.svg",
  SHOPPING_CART: "/images/icons/shopping-cart.svg",
  PARFUME1_ICON: "/images/icons/perfume1.svg",
  PARFUME2_ICON: "/images/icons/perfume2.svg",
  PARFUME3_ICON: "/images/icons/perfume3.svg",
  PARFUME4_ICON: "/images/icons/perfume4.svg",
  PARFUME5_ICON: "/images/icons/perfume5.svg",
  HEART_OUTLINE: "/images/icons/heartOutline.svg",
  HEART_FILL: "/images/icons/heartFill.svg",
  STAR_ICON: "/images/icons/vector.svg",
  STAR_ICON_OUTLINE: "/images/icons/vectorOutFill.svg",
  ARROW_RIGHT_ICON: "/images/icons/rightArrow.svg",
  ARROW_LEFT_ICON: "/images/icons/leftArrow.svg",
  BLOG_IMAGE1: "/images/icons/image 6.svg",
  BLOG_IMAGE2: "/images/icons/Rectangle 39.svg",
  BLOG_IMAGE3: "/images/icons/Rectangle 104.svg",
} as const;
